
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const NameProvider = {
  GOOGLE: 'GOOGLE',
  LOCAL: 'LOCAL'
} as const

export type NameProvider = (typeof NameProvider)[keyof typeof NameProvider]
