services:
  postgres:
    image: postgres:16-alpine
    container_name: learning_language_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports: 
      - "127.0.0.1:5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  redis:
    image: redis:7-alpine
    container_name: learning_language_redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "127.0.0.1:6378:6379"
    volumes:
      - redisdata:/data

  backend:
    image: node:20-alpine
    container_name: learning_language_backend
    working_dir: /app
    volumes:
      - ./back_end:/app
      - /app/node_modules
    ports:
      - "127.0.0.1:3000:3000"
    env_file:
      - ./back_end/.env
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?schema=public
      - REDIS_HOST=redis
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command:  sh -c "npm install && npx prisma generate && npx prisma db push && npm run start:dev"
    depends_on:
      - postgres
      - redis
  
  frontend:
    image: node:20-alpine
    container_name: learning_language_frontend
    working_dir: /app
    volumes:
      - ./FRONT_END:/app
      - /app/node_modules
    ports:
      - "127.0.0.1:5173:5173"
    env_file:
      - ./FRONT_END/.env
    environment:
      - VITE_API_URL=http://localhost:3000
    command:  sh -c "npm install && npm run dev -- --host"
    depends_on:
      - backend
volumes:
    pgdata:
    redisdata:
