
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `HeartEmoji` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums.js"
import type * as Prisma from "../internal/prismaNamespace.js"

/**
 * Model HeartEmoji
 * 
 */
export type HeartEmojiModel = runtime.Types.Result.DefaultSelection<Prisma.$HeartEmojiPayload>

export type AggregateHeartEmoji = {
  _count: HeartEmojiCountAggregateOutputType | null
  _avg: HeartEmojiAvgAggregateOutputType | null
  _sum: HeartEmojiSumAggregateOutputType | null
  _min: HeartEmojiMinAggregateOutputType | null
  _max: HeartEmojiMaxAggregateOutputType | null
}

export type HeartEmojiAvgAggregateOutputType = {
  id: number | null
  postId: number | null
}

export type HeartEmojiSumAggregateOutputType = {
  id: number | null
  postId: number | null
}

export type HeartEmojiMinAggregateOutputType = {
  id: number | null
  createdAt: Date | null
  authorId: string | null
  postId: number | null
}

export type HeartEmojiMaxAggregateOutputType = {
  id: number | null
  createdAt: Date | null
  authorId: string | null
  postId: number | null
}

export type HeartEmojiCountAggregateOutputType = {
  id: number
  createdAt: number
  authorId: number
  postId: number
  _all: number
}


export type HeartEmojiAvgAggregateInputType = {
  id?: true
  postId?: true
}

export type HeartEmojiSumAggregateInputType = {
  id?: true
  postId?: true
}

export type HeartEmojiMinAggregateInputType = {
  id?: true
  createdAt?: true
  authorId?: true
  postId?: true
}

export type HeartEmojiMaxAggregateInputType = {
  id?: true
  createdAt?: true
  authorId?: true
  postId?: true
}

export type HeartEmojiCountAggregateInputType = {
  id?: true
  createdAt?: true
  authorId?: true
  postId?: true
  _all?: true
}

export type HeartEmojiAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which HeartEmoji to aggregate.
   */
  where?: Prisma.HeartEmojiWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HeartEmojis to fetch.
   */
  orderBy?: Prisma.HeartEmojiOrderByWithRelationInput | Prisma.HeartEmojiOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.HeartEmojiWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HeartEmojis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HeartEmojis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned HeartEmojis
  **/
  _count?: true | HeartEmojiCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: HeartEmojiAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: HeartEmojiSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: HeartEmojiMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: HeartEmojiMaxAggregateInputType
}

export type GetHeartEmojiAggregateType<T extends HeartEmojiAggregateArgs> = {
      [P in keyof T & keyof AggregateHeartEmoji]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateHeartEmoji[P]>
    : Prisma.GetScalarType<T[P], AggregateHeartEmoji[P]>
}




export type HeartEmojiGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.HeartEmojiWhereInput
  orderBy?: Prisma.HeartEmojiOrderByWithAggregationInput | Prisma.HeartEmojiOrderByWithAggregationInput[]
  by: Prisma.HeartEmojiScalarFieldEnum[] | Prisma.HeartEmojiScalarFieldEnum
  having?: Prisma.HeartEmojiScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: HeartEmojiCountAggregateInputType | true
  _avg?: HeartEmojiAvgAggregateInputType
  _sum?: HeartEmojiSumAggregateInputType
  _min?: HeartEmojiMinAggregateInputType
  _max?: HeartEmojiMaxAggregateInputType
}

export type HeartEmojiGroupByOutputType = {
  id: number
  createdAt: Date
  authorId: string
  postId: number
  _count: HeartEmojiCountAggregateOutputType | null
  _avg: HeartEmojiAvgAggregateOutputType | null
  _sum: HeartEmojiSumAggregateOutputType | null
  _min: HeartEmojiMinAggregateOutputType | null
  _max: HeartEmojiMaxAggregateOutputType | null
}

export type GetHeartEmojiGroupByPayload<T extends HeartEmojiGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<HeartEmojiGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof HeartEmojiGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], HeartEmojiGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], HeartEmojiGroupByOutputType[P]>
      }
    >
  >



export type HeartEmojiWhereInput = {
  AND?: Prisma.HeartEmojiWhereInput | Prisma.HeartEmojiWhereInput[]
  OR?: Prisma.HeartEmojiWhereInput[]
  NOT?: Prisma.HeartEmojiWhereInput | Prisma.HeartEmojiWhereInput[]
  id?: Prisma.IntFilter<"HeartEmoji"> | number
  createdAt?: Prisma.DateTimeFilter<"HeartEmoji"> | Date | string
  authorId?: Prisma.StringFilter<"HeartEmoji"> | string
  postId?: Prisma.IntFilter<"HeartEmoji"> | number
  author?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  post?: Prisma.XOR<Prisma.PostScalarRelationFilter, Prisma.PostWhereInput>
}

export type HeartEmojiOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  author?: Prisma.UserOrderByWithRelationInput
  post?: Prisma.PostOrderByWithRelationInput
}

export type HeartEmojiWhereUniqueInput = Prisma.AtLeast<{
  id?: number
  authorId_postId?: Prisma.HeartEmojiAuthorIdPostIdCompoundUniqueInput
  AND?: Prisma.HeartEmojiWhereInput | Prisma.HeartEmojiWhereInput[]
  OR?: Prisma.HeartEmojiWhereInput[]
  NOT?: Prisma.HeartEmojiWhereInput | Prisma.HeartEmojiWhereInput[]
  createdAt?: Prisma.DateTimeFilter<"HeartEmoji"> | Date | string
  authorId?: Prisma.StringFilter<"HeartEmoji"> | string
  postId?: Prisma.IntFilter<"HeartEmoji"> | number
  author?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  post?: Prisma.XOR<Prisma.PostScalarRelationFilter, Prisma.PostWhereInput>
}, "id" | "authorId_postId">

export type HeartEmojiOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  postId?: Prisma.SortOrder
  _count?: Prisma.HeartEmojiCountOrderByAggregateInput
  _avg?: Prisma.HeartEmojiAvgOrderByAggregateInput
  _max?: Prisma.HeartEmojiMaxOrderByAggregateInput
  _min?: Prisma.HeartEmojiMinOrderByAggregateInput
  _sum?: Prisma.HeartEmojiSumOrderByAggregateInput
}

export type HeartEmojiScalarWhereWithAggregatesInput = {
  AND?: Prisma.HeartEmojiScalarWhereWithAggregatesInput | Prisma.HeartEmojiScalarWhereWithAggregatesInput[]
  OR?: Prisma.HeartEmojiScalarWhereWithAggregatesInput[]
  NOT?: Prisma.HeartEmojiScalarWhereWithAggregatesInput | Prisma.HeartEmojiScalarWhereWithAggregatesInput[]
  id?: Prisma.IntWithAggregatesFilter<"HeartEmoji"> | number
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"HeartEmoji"> | Date | string
  authorId?: Prisma.StringWithAggregatesFilter<"HeartEmoji"> | string
  postId?: Prisma.IntWithAggregatesFilter<"HeartEmoji"> | number
}

export type HeartEmojiCreateInput = {
  createdAt?: Date | string
  author: Prisma.UserCreateNestedOneWithoutHeartEmojisInput
  post: Prisma.PostCreateNestedOneWithoutHeartEmojisInput
}

export type HeartEmojiUncheckedCreateInput = {
  id?: number
  createdAt?: Date | string
  authorId: string
  postId: number
}

export type HeartEmojiUpdateInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  author?: Prisma.UserUpdateOneRequiredWithoutHeartEmojisNestedInput
  post?: Prisma.PostUpdateOneRequiredWithoutHeartEmojisNestedInput
}

export type HeartEmojiUncheckedUpdateInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  postId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type HeartEmojiCreateManyInput = {
  id?: number
  createdAt?: Date | string
  authorId: string
  postId: number
}

export type HeartEmojiUpdateManyMutationInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type HeartEmojiUncheckedUpdateManyInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
  postId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type HeartEmojiListRelationFilter = {
  every?: Prisma.HeartEmojiWhereInput
  some?: Prisma.HeartEmojiWhereInput
  none?: Prisma.HeartEmojiWhereInput
}

export type HeartEmojiOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type HeartEmojiAuthorIdPostIdCompoundUniqueInput = {
  authorId: string
  postId: number
}

export type HeartEmojiCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  postId?: Prisma.SortOrder
}

export type HeartEmojiAvgOrderByAggregateInput = {
  id?: Prisma.SortOrder
  postId?: Prisma.SortOrder
}

export type HeartEmojiMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  postId?: Prisma.SortOrder
}

export type HeartEmojiMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  authorId?: Prisma.SortOrder
  postId?: Prisma.SortOrder
}

export type HeartEmojiSumOrderByAggregateInput = {
  id?: Prisma.SortOrder
  postId?: Prisma.SortOrder
}

export type HeartEmojiCreateNestedManyWithoutAuthorInput = {
  create?: Prisma.XOR<Prisma.HeartEmojiCreateWithoutAuthorInput, Prisma.HeartEmojiUncheckedCreateWithoutAuthorInput> | Prisma.HeartEmojiCreateWithoutAuthorInput[] | Prisma.HeartEmojiUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.HeartEmojiCreateOrConnectWithoutAuthorInput | Prisma.HeartEmojiCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.HeartEmojiCreateManyAuthorInputEnvelope
  connect?: Prisma.HeartEmojiWhereUniqueInput | Prisma.HeartEmojiWhereUniqueInput[]
}

export type HeartEmojiUncheckedCreateNestedManyWithoutAuthorInput = {
  create?: Prisma.XOR<Prisma.HeartEmojiCreateWithoutAuthorInput, Prisma.HeartEmojiUncheckedCreateWithoutAuthorInput> | Prisma.HeartEmojiCreateWithoutAuthorInput[] | Prisma.HeartEmojiUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.HeartEmojiCreateOrConnectWithoutAuthorInput | Prisma.HeartEmojiCreateOrConnectWithoutAuthorInput[]
  createMany?: Prisma.HeartEmojiCreateManyAuthorInputEnvelope
  connect?: Prisma.HeartEmojiWhereUniqueInput | Prisma.HeartEmojiWhereUniqueInput[]
}

export type HeartEmojiUpdateManyWithoutAuthorNestedInput = {
  create?: Prisma.XOR<Prisma.HeartEmojiCreateWithoutAuthorInput, Prisma.HeartEmojiUncheckedCreateWithoutAuthorInput> | Prisma.HeartEmojiCreateWithoutAuthorInput[] | Prisma.HeartEmojiUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.HeartEmojiCreateOrConnectWithoutAuthorInput | Prisma.HeartEmojiCreateOrConnectWithoutAuthorInput[]
  upsert?: Prisma.HeartEmojiUpsertWithWhereUniqueWithoutAuthorInput | Prisma.HeartEmojiUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.HeartEmojiCreateManyAuthorInputEnvelope
  set?: Prisma.HeartEmojiWhereUniqueInput | Prisma.HeartEmojiWhereUniqueInput[]
  disconnect?: Prisma.HeartEmojiWhereUniqueInput | Prisma.HeartEmojiWhereUniqueInput[]
  delete?: Prisma.HeartEmojiWhereUniqueInput | Prisma.HeartEmojiWhereUniqueInput[]
  connect?: Prisma.HeartEmojiWhereUniqueInput | Prisma.HeartEmojiWhereUniqueInput[]
  update?: Prisma.HeartEmojiUpdateWithWhereUniqueWithoutAuthorInput | Prisma.HeartEmojiUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?: Prisma.HeartEmojiUpdateManyWithWhereWithoutAuthorInput | Prisma.HeartEmojiUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.HeartEmojiScalarWhereInput | Prisma.HeartEmojiScalarWhereInput[]
}

export type HeartEmojiUncheckedUpdateManyWithoutAuthorNestedInput = {
  create?: Prisma.XOR<Prisma.HeartEmojiCreateWithoutAuthorInput, Prisma.HeartEmojiUncheckedCreateWithoutAuthorInput> | Prisma.HeartEmojiCreateWithoutAuthorInput[] | Prisma.HeartEmojiUncheckedCreateWithoutAuthorInput[]
  connectOrCreate?: Prisma.HeartEmojiCreateOrConnectWithoutAuthorInput | Prisma.HeartEmojiCreateOrConnectWithoutAuthorInput[]
  upsert?: Prisma.HeartEmojiUpsertWithWhereUniqueWithoutAuthorInput | Prisma.HeartEmojiUpsertWithWhereUniqueWithoutAuthorInput[]
  createMany?: Prisma.HeartEmojiCreateManyAuthorInputEnvelope
  set?: Prisma.HeartEmojiWhereUniqueInput | Prisma.HeartEmojiWhereUniqueInput[]
  disconnect?: Prisma.HeartEmojiWhereUniqueInput | Prisma.HeartEmojiWhereUniqueInput[]
  delete?: Prisma.HeartEmojiWhereUniqueInput | Prisma.HeartEmojiWhereUniqueInput[]
  connect?: Prisma.HeartEmojiWhereUniqueInput | Prisma.HeartEmojiWhereUniqueInput[]
  update?: Prisma.HeartEmojiUpdateWithWhereUniqueWithoutAuthorInput | Prisma.HeartEmojiUpdateWithWhereUniqueWithoutAuthorInput[]
  updateMany?: Prisma.HeartEmojiUpdateManyWithWhereWithoutAuthorInput | Prisma.HeartEmojiUpdateManyWithWhereWithoutAuthorInput[]
  deleteMany?: Prisma.HeartEmojiScalarWhereInput | Prisma.HeartEmojiScalarWhereInput[]
}

export type HeartEmojiCreateNestedManyWithoutPostInput = {
  create?: Prisma.XOR<Prisma.HeartEmojiCreateWithoutPostInput, Prisma.HeartEmojiUncheckedCreateWithoutPostInput> | Prisma.HeartEmojiCreateWithoutPostInput[] | Prisma.HeartEmojiUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.HeartEmojiCreateOrConnectWithoutPostInput | Prisma.HeartEmojiCreateOrConnectWithoutPostInput[]
  createMany?: Prisma.HeartEmojiCreateManyPostInputEnvelope
  connect?: Prisma.HeartEmojiWhereUniqueInput | Prisma.HeartEmojiWhereUniqueInput[]
}

export type HeartEmojiUncheckedCreateNestedManyWithoutPostInput = {
  create?: Prisma.XOR<Prisma.HeartEmojiCreateWithoutPostInput, Prisma.HeartEmojiUncheckedCreateWithoutPostInput> | Prisma.HeartEmojiCreateWithoutPostInput[] | Prisma.HeartEmojiUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.HeartEmojiCreateOrConnectWithoutPostInput | Prisma.HeartEmojiCreateOrConnectWithoutPostInput[]
  createMany?: Prisma.HeartEmojiCreateManyPostInputEnvelope
  connect?: Prisma.HeartEmojiWhereUniqueInput | Prisma.HeartEmojiWhereUniqueInput[]
}

export type HeartEmojiUpdateManyWithoutPostNestedInput = {
  create?: Prisma.XOR<Prisma.HeartEmojiCreateWithoutPostInput, Prisma.HeartEmojiUncheckedCreateWithoutPostInput> | Prisma.HeartEmojiCreateWithoutPostInput[] | Prisma.HeartEmojiUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.HeartEmojiCreateOrConnectWithoutPostInput | Prisma.HeartEmojiCreateOrConnectWithoutPostInput[]
  upsert?: Prisma.HeartEmojiUpsertWithWhereUniqueWithoutPostInput | Prisma.HeartEmojiUpsertWithWhereUniqueWithoutPostInput[]
  createMany?: Prisma.HeartEmojiCreateManyPostInputEnvelope
  set?: Prisma.HeartEmojiWhereUniqueInput | Prisma.HeartEmojiWhereUniqueInput[]
  disconnect?: Prisma.HeartEmojiWhereUniqueInput | Prisma.HeartEmojiWhereUniqueInput[]
  delete?: Prisma.HeartEmojiWhereUniqueInput | Prisma.HeartEmojiWhereUniqueInput[]
  connect?: Prisma.HeartEmojiWhereUniqueInput | Prisma.HeartEmojiWhereUniqueInput[]
  update?: Prisma.HeartEmojiUpdateWithWhereUniqueWithoutPostInput | Prisma.HeartEmojiUpdateWithWhereUniqueWithoutPostInput[]
  updateMany?: Prisma.HeartEmojiUpdateManyWithWhereWithoutPostInput | Prisma.HeartEmojiUpdateManyWithWhereWithoutPostInput[]
  deleteMany?: Prisma.HeartEmojiScalarWhereInput | Prisma.HeartEmojiScalarWhereInput[]
}

export type HeartEmojiUncheckedUpdateManyWithoutPostNestedInput = {
  create?: Prisma.XOR<Prisma.HeartEmojiCreateWithoutPostInput, Prisma.HeartEmojiUncheckedCreateWithoutPostInput> | Prisma.HeartEmojiCreateWithoutPostInput[] | Prisma.HeartEmojiUncheckedCreateWithoutPostInput[]
  connectOrCreate?: Prisma.HeartEmojiCreateOrConnectWithoutPostInput | Prisma.HeartEmojiCreateOrConnectWithoutPostInput[]
  upsert?: Prisma.HeartEmojiUpsertWithWhereUniqueWithoutPostInput | Prisma.HeartEmojiUpsertWithWhereUniqueWithoutPostInput[]
  createMany?: Prisma.HeartEmojiCreateManyPostInputEnvelope
  set?: Prisma.HeartEmojiWhereUniqueInput | Prisma.HeartEmojiWhereUniqueInput[]
  disconnect?: Prisma.HeartEmojiWhereUniqueInput | Prisma.HeartEmojiWhereUniqueInput[]
  delete?: Prisma.HeartEmojiWhereUniqueInput | Prisma.HeartEmojiWhereUniqueInput[]
  connect?: Prisma.HeartEmojiWhereUniqueInput | Prisma.HeartEmojiWhereUniqueInput[]
  update?: Prisma.HeartEmojiUpdateWithWhereUniqueWithoutPostInput | Prisma.HeartEmojiUpdateWithWhereUniqueWithoutPostInput[]
  updateMany?: Prisma.HeartEmojiUpdateManyWithWhereWithoutPostInput | Prisma.HeartEmojiUpdateManyWithWhereWithoutPostInput[]
  deleteMany?: Prisma.HeartEmojiScalarWhereInput | Prisma.HeartEmojiScalarWhereInput[]
}

export type HeartEmojiCreateWithoutAuthorInput = {
  createdAt?: Date | string
  post: Prisma.PostCreateNestedOneWithoutHeartEmojisInput
}

export type HeartEmojiUncheckedCreateWithoutAuthorInput = {
  id?: number
  createdAt?: Date | string
  postId: number
}

export type HeartEmojiCreateOrConnectWithoutAuthorInput = {
  where: Prisma.HeartEmojiWhereUniqueInput
  create: Prisma.XOR<Prisma.HeartEmojiCreateWithoutAuthorInput, Prisma.HeartEmojiUncheckedCreateWithoutAuthorInput>
}

export type HeartEmojiCreateManyAuthorInputEnvelope = {
  data: Prisma.HeartEmojiCreateManyAuthorInput | Prisma.HeartEmojiCreateManyAuthorInput[]
  skipDuplicates?: boolean
}

export type HeartEmojiUpsertWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.HeartEmojiWhereUniqueInput
  update: Prisma.XOR<Prisma.HeartEmojiUpdateWithoutAuthorInput, Prisma.HeartEmojiUncheckedUpdateWithoutAuthorInput>
  create: Prisma.XOR<Prisma.HeartEmojiCreateWithoutAuthorInput, Prisma.HeartEmojiUncheckedCreateWithoutAuthorInput>
}

export type HeartEmojiUpdateWithWhereUniqueWithoutAuthorInput = {
  where: Prisma.HeartEmojiWhereUniqueInput
  data: Prisma.XOR<Prisma.HeartEmojiUpdateWithoutAuthorInput, Prisma.HeartEmojiUncheckedUpdateWithoutAuthorInput>
}

export type HeartEmojiUpdateManyWithWhereWithoutAuthorInput = {
  where: Prisma.HeartEmojiScalarWhereInput
  data: Prisma.XOR<Prisma.HeartEmojiUpdateManyMutationInput, Prisma.HeartEmojiUncheckedUpdateManyWithoutAuthorInput>
}

export type HeartEmojiScalarWhereInput = {
  AND?: Prisma.HeartEmojiScalarWhereInput | Prisma.HeartEmojiScalarWhereInput[]
  OR?: Prisma.HeartEmojiScalarWhereInput[]
  NOT?: Prisma.HeartEmojiScalarWhereInput | Prisma.HeartEmojiScalarWhereInput[]
  id?: Prisma.IntFilter<"HeartEmoji"> | number
  createdAt?: Prisma.DateTimeFilter<"HeartEmoji"> | Date | string
  authorId?: Prisma.StringFilter<"HeartEmoji"> | string
  postId?: Prisma.IntFilter<"HeartEmoji"> | number
}

export type HeartEmojiCreateWithoutPostInput = {
  createdAt?: Date | string
  author: Prisma.UserCreateNestedOneWithoutHeartEmojisInput
}

export type HeartEmojiUncheckedCreateWithoutPostInput = {
  id?: number
  createdAt?: Date | string
  authorId: string
}

export type HeartEmojiCreateOrConnectWithoutPostInput = {
  where: Prisma.HeartEmojiWhereUniqueInput
  create: Prisma.XOR<Prisma.HeartEmojiCreateWithoutPostInput, Prisma.HeartEmojiUncheckedCreateWithoutPostInput>
}

export type HeartEmojiCreateManyPostInputEnvelope = {
  data: Prisma.HeartEmojiCreateManyPostInput | Prisma.HeartEmojiCreateManyPostInput[]
  skipDuplicates?: boolean
}

export type HeartEmojiUpsertWithWhereUniqueWithoutPostInput = {
  where: Prisma.HeartEmojiWhereUniqueInput
  update: Prisma.XOR<Prisma.HeartEmojiUpdateWithoutPostInput, Prisma.HeartEmojiUncheckedUpdateWithoutPostInput>
  create: Prisma.XOR<Prisma.HeartEmojiCreateWithoutPostInput, Prisma.HeartEmojiUncheckedCreateWithoutPostInput>
}

export type HeartEmojiUpdateWithWhereUniqueWithoutPostInput = {
  where: Prisma.HeartEmojiWhereUniqueInput
  data: Prisma.XOR<Prisma.HeartEmojiUpdateWithoutPostInput, Prisma.HeartEmojiUncheckedUpdateWithoutPostInput>
}

export type HeartEmojiUpdateManyWithWhereWithoutPostInput = {
  where: Prisma.HeartEmojiScalarWhereInput
  data: Prisma.XOR<Prisma.HeartEmojiUpdateManyMutationInput, Prisma.HeartEmojiUncheckedUpdateManyWithoutPostInput>
}

export type HeartEmojiCreateManyAuthorInput = {
  id?: number
  createdAt?: Date | string
  postId: number
}

export type HeartEmojiUpdateWithoutAuthorInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  post?: Prisma.PostUpdateOneRequiredWithoutHeartEmojisNestedInput
}

export type HeartEmojiUncheckedUpdateWithoutAuthorInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  postId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type HeartEmojiUncheckedUpdateManyWithoutAuthorInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  postId?: Prisma.IntFieldUpdateOperationsInput | number
}

export type HeartEmojiCreateManyPostInput = {
  id?: number
  createdAt?: Date | string
  authorId: string
}

export type HeartEmojiUpdateWithoutPostInput = {
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  author?: Prisma.UserUpdateOneRequiredWithoutHeartEmojisNestedInput
}

export type HeartEmojiUncheckedUpdateWithoutPostInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
}

export type HeartEmojiUncheckedUpdateManyWithoutPostInput = {
  id?: Prisma.IntFieldUpdateOperationsInput | number
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  authorId?: Prisma.StringFieldUpdateOperationsInput | string
}



export type HeartEmojiSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  authorId?: boolean
  postId?: boolean
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}, ExtArgs["result"]["heartEmoji"]>

export type HeartEmojiSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  authorId?: boolean
  postId?: boolean
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}, ExtArgs["result"]["heartEmoji"]>

export type HeartEmojiSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  createdAt?: boolean
  authorId?: boolean
  postId?: boolean
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}, ExtArgs["result"]["heartEmoji"]>

export type HeartEmojiSelectScalar = {
  id?: boolean
  createdAt?: boolean
  authorId?: boolean
  postId?: boolean
}

export type HeartEmojiOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "createdAt" | "authorId" | "postId", ExtArgs["result"]["heartEmoji"]>
export type HeartEmojiInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}
export type HeartEmojiIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}
export type HeartEmojiIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  author?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  post?: boolean | Prisma.PostDefaultArgs<ExtArgs>
}

export type $HeartEmojiPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "HeartEmoji"
  objects: {
    author: Prisma.$UserPayload<ExtArgs>
    post: Prisma.$PostPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: number
    createdAt: Date
    authorId: string
    postId: number
  }, ExtArgs["result"]["heartEmoji"]>
  composites: {}
}

export type HeartEmojiGetPayload<S extends boolean | null | undefined | HeartEmojiDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$HeartEmojiPayload, S>

export type HeartEmojiCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<HeartEmojiFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: HeartEmojiCountAggregateInputType | true
  }

export interface HeartEmojiDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['HeartEmoji'], meta: { name: 'HeartEmoji' } }
  /**
   * Find zero or one HeartEmoji that matches the filter.
   * @param {HeartEmojiFindUniqueArgs} args - Arguments to find a HeartEmoji
   * @example
   * // Get one HeartEmoji
   * const heartEmoji = await prisma.heartEmoji.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends HeartEmojiFindUniqueArgs>(args: Prisma.SelectSubset<T, HeartEmojiFindUniqueArgs<ExtArgs>>): Prisma.Prisma__HeartEmojiClient<runtime.Types.Result.GetResult<Prisma.$HeartEmojiPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one HeartEmoji that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {HeartEmojiFindUniqueOrThrowArgs} args - Arguments to find a HeartEmoji
   * @example
   * // Get one HeartEmoji
   * const heartEmoji = await prisma.heartEmoji.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends HeartEmojiFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, HeartEmojiFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__HeartEmojiClient<runtime.Types.Result.GetResult<Prisma.$HeartEmojiPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first HeartEmoji that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HeartEmojiFindFirstArgs} args - Arguments to find a HeartEmoji
   * @example
   * // Get one HeartEmoji
   * const heartEmoji = await prisma.heartEmoji.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends HeartEmojiFindFirstArgs>(args?: Prisma.SelectSubset<T, HeartEmojiFindFirstArgs<ExtArgs>>): Prisma.Prisma__HeartEmojiClient<runtime.Types.Result.GetResult<Prisma.$HeartEmojiPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first HeartEmoji that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HeartEmojiFindFirstOrThrowArgs} args - Arguments to find a HeartEmoji
   * @example
   * // Get one HeartEmoji
   * const heartEmoji = await prisma.heartEmoji.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends HeartEmojiFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, HeartEmojiFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__HeartEmojiClient<runtime.Types.Result.GetResult<Prisma.$HeartEmojiPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more HeartEmojis that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HeartEmojiFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all HeartEmojis
   * const heartEmojis = await prisma.heartEmoji.findMany()
   * 
   * // Get first 10 HeartEmojis
   * const heartEmojis = await prisma.heartEmoji.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const heartEmojiWithIdOnly = await prisma.heartEmoji.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends HeartEmojiFindManyArgs>(args?: Prisma.SelectSubset<T, HeartEmojiFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HeartEmojiPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a HeartEmoji.
   * @param {HeartEmojiCreateArgs} args - Arguments to create a HeartEmoji.
   * @example
   * // Create one HeartEmoji
   * const HeartEmoji = await prisma.heartEmoji.create({
   *   data: {
   *     // ... data to create a HeartEmoji
   *   }
   * })
   * 
   */
  create<T extends HeartEmojiCreateArgs>(args: Prisma.SelectSubset<T, HeartEmojiCreateArgs<ExtArgs>>): Prisma.Prisma__HeartEmojiClient<runtime.Types.Result.GetResult<Prisma.$HeartEmojiPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many HeartEmojis.
   * @param {HeartEmojiCreateManyArgs} args - Arguments to create many HeartEmojis.
   * @example
   * // Create many HeartEmojis
   * const heartEmoji = await prisma.heartEmoji.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends HeartEmojiCreateManyArgs>(args?: Prisma.SelectSubset<T, HeartEmojiCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many HeartEmojis and returns the data saved in the database.
   * @param {HeartEmojiCreateManyAndReturnArgs} args - Arguments to create many HeartEmojis.
   * @example
   * // Create many HeartEmojis
   * const heartEmoji = await prisma.heartEmoji.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many HeartEmojis and only return the `id`
   * const heartEmojiWithIdOnly = await prisma.heartEmoji.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends HeartEmojiCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, HeartEmojiCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HeartEmojiPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a HeartEmoji.
   * @param {HeartEmojiDeleteArgs} args - Arguments to delete one HeartEmoji.
   * @example
   * // Delete one HeartEmoji
   * const HeartEmoji = await prisma.heartEmoji.delete({
   *   where: {
   *     // ... filter to delete one HeartEmoji
   *   }
   * })
   * 
   */
  delete<T extends HeartEmojiDeleteArgs>(args: Prisma.SelectSubset<T, HeartEmojiDeleteArgs<ExtArgs>>): Prisma.Prisma__HeartEmojiClient<runtime.Types.Result.GetResult<Prisma.$HeartEmojiPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one HeartEmoji.
   * @param {HeartEmojiUpdateArgs} args - Arguments to update one HeartEmoji.
   * @example
   * // Update one HeartEmoji
   * const heartEmoji = await prisma.heartEmoji.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends HeartEmojiUpdateArgs>(args: Prisma.SelectSubset<T, HeartEmojiUpdateArgs<ExtArgs>>): Prisma.Prisma__HeartEmojiClient<runtime.Types.Result.GetResult<Prisma.$HeartEmojiPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more HeartEmojis.
   * @param {HeartEmojiDeleteManyArgs} args - Arguments to filter HeartEmojis to delete.
   * @example
   * // Delete a few HeartEmojis
   * const { count } = await prisma.heartEmoji.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends HeartEmojiDeleteManyArgs>(args?: Prisma.SelectSubset<T, HeartEmojiDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more HeartEmojis.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HeartEmojiUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many HeartEmojis
   * const heartEmoji = await prisma.heartEmoji.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends HeartEmojiUpdateManyArgs>(args: Prisma.SelectSubset<T, HeartEmojiUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more HeartEmojis and returns the data updated in the database.
   * @param {HeartEmojiUpdateManyAndReturnArgs} args - Arguments to update many HeartEmojis.
   * @example
   * // Update many HeartEmojis
   * const heartEmoji = await prisma.heartEmoji.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more HeartEmojis and only return the `id`
   * const heartEmojiWithIdOnly = await prisma.heartEmoji.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends HeartEmojiUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, HeartEmojiUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$HeartEmojiPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one HeartEmoji.
   * @param {HeartEmojiUpsertArgs} args - Arguments to update or create a HeartEmoji.
   * @example
   * // Update or create a HeartEmoji
   * const heartEmoji = await prisma.heartEmoji.upsert({
   *   create: {
   *     // ... data to create a HeartEmoji
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the HeartEmoji we want to update
   *   }
   * })
   */
  upsert<T extends HeartEmojiUpsertArgs>(args: Prisma.SelectSubset<T, HeartEmojiUpsertArgs<ExtArgs>>): Prisma.Prisma__HeartEmojiClient<runtime.Types.Result.GetResult<Prisma.$HeartEmojiPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of HeartEmojis.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HeartEmojiCountArgs} args - Arguments to filter HeartEmojis to count.
   * @example
   * // Count the number of HeartEmojis
   * const count = await prisma.heartEmoji.count({
   *   where: {
   *     // ... the filter for the HeartEmojis we want to count
   *   }
   * })
  **/
  count<T extends HeartEmojiCountArgs>(
    args?: Prisma.Subset<T, HeartEmojiCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], HeartEmojiCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a HeartEmoji.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HeartEmojiAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends HeartEmojiAggregateArgs>(args: Prisma.Subset<T, HeartEmojiAggregateArgs>): Prisma.PrismaPromise<GetHeartEmojiAggregateType<T>>

  /**
   * Group by HeartEmoji.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {HeartEmojiGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends HeartEmojiGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: HeartEmojiGroupByArgs['orderBy'] }
      : { orderBy?: HeartEmojiGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, HeartEmojiGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetHeartEmojiGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the HeartEmoji model
 */
readonly fields: HeartEmojiFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for HeartEmoji.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__HeartEmojiClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  author<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  post<T extends Prisma.PostDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.PostDefaultArgs<ExtArgs>>): Prisma.Prisma__PostClient<runtime.Types.Result.GetResult<Prisma.$PostPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the HeartEmoji model
 */
export interface HeartEmojiFieldRefs {
  readonly id: Prisma.FieldRef<"HeartEmoji", 'Int'>
  readonly createdAt: Prisma.FieldRef<"HeartEmoji", 'DateTime'>
  readonly authorId: Prisma.FieldRef<"HeartEmoji", 'String'>
  readonly postId: Prisma.FieldRef<"HeartEmoji", 'Int'>
}
    

// Custom InputTypes
/**
 * HeartEmoji findUnique
 */
export type HeartEmojiFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeartEmoji
   */
  select?: Prisma.HeartEmojiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HeartEmoji
   */
  omit?: Prisma.HeartEmojiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HeartEmojiInclude<ExtArgs> | null
  /**
   * Filter, which HeartEmoji to fetch.
   */
  where: Prisma.HeartEmojiWhereUniqueInput
}

/**
 * HeartEmoji findUniqueOrThrow
 */
export type HeartEmojiFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeartEmoji
   */
  select?: Prisma.HeartEmojiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HeartEmoji
   */
  omit?: Prisma.HeartEmojiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HeartEmojiInclude<ExtArgs> | null
  /**
   * Filter, which HeartEmoji to fetch.
   */
  where: Prisma.HeartEmojiWhereUniqueInput
}

/**
 * HeartEmoji findFirst
 */
export type HeartEmojiFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeartEmoji
   */
  select?: Prisma.HeartEmojiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HeartEmoji
   */
  omit?: Prisma.HeartEmojiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HeartEmojiInclude<ExtArgs> | null
  /**
   * Filter, which HeartEmoji to fetch.
   */
  where?: Prisma.HeartEmojiWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HeartEmojis to fetch.
   */
  orderBy?: Prisma.HeartEmojiOrderByWithRelationInput | Prisma.HeartEmojiOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for HeartEmojis.
   */
  cursor?: Prisma.HeartEmojiWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HeartEmojis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HeartEmojis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HeartEmojis.
   */
  distinct?: Prisma.HeartEmojiScalarFieldEnum | Prisma.HeartEmojiScalarFieldEnum[]
}

/**
 * HeartEmoji findFirstOrThrow
 */
export type HeartEmojiFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeartEmoji
   */
  select?: Prisma.HeartEmojiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HeartEmoji
   */
  omit?: Prisma.HeartEmojiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HeartEmojiInclude<ExtArgs> | null
  /**
   * Filter, which HeartEmoji to fetch.
   */
  where?: Prisma.HeartEmojiWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HeartEmojis to fetch.
   */
  orderBy?: Prisma.HeartEmojiOrderByWithRelationInput | Prisma.HeartEmojiOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for HeartEmojis.
   */
  cursor?: Prisma.HeartEmojiWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HeartEmojis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HeartEmojis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HeartEmojis.
   */
  distinct?: Prisma.HeartEmojiScalarFieldEnum | Prisma.HeartEmojiScalarFieldEnum[]
}

/**
 * HeartEmoji findMany
 */
export type HeartEmojiFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeartEmoji
   */
  select?: Prisma.HeartEmojiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HeartEmoji
   */
  omit?: Prisma.HeartEmojiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HeartEmojiInclude<ExtArgs> | null
  /**
   * Filter, which HeartEmojis to fetch.
   */
  where?: Prisma.HeartEmojiWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of HeartEmojis to fetch.
   */
  orderBy?: Prisma.HeartEmojiOrderByWithRelationInput | Prisma.HeartEmojiOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing HeartEmojis.
   */
  cursor?: Prisma.HeartEmojiWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` HeartEmojis from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` HeartEmojis.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of HeartEmojis.
   */
  distinct?: Prisma.HeartEmojiScalarFieldEnum | Prisma.HeartEmojiScalarFieldEnum[]
}

/**
 * HeartEmoji create
 */
export type HeartEmojiCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeartEmoji
   */
  select?: Prisma.HeartEmojiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HeartEmoji
   */
  omit?: Prisma.HeartEmojiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HeartEmojiInclude<ExtArgs> | null
  /**
   * The data needed to create a HeartEmoji.
   */
  data: Prisma.XOR<Prisma.HeartEmojiCreateInput, Prisma.HeartEmojiUncheckedCreateInput>
}

/**
 * HeartEmoji createMany
 */
export type HeartEmojiCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many HeartEmojis.
   */
  data: Prisma.HeartEmojiCreateManyInput | Prisma.HeartEmojiCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * HeartEmoji createManyAndReturn
 */
export type HeartEmojiCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeartEmoji
   */
  select?: Prisma.HeartEmojiSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the HeartEmoji
   */
  omit?: Prisma.HeartEmojiOmit<ExtArgs> | null
  /**
   * The data used to create many HeartEmojis.
   */
  data: Prisma.HeartEmojiCreateManyInput | Prisma.HeartEmojiCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HeartEmojiIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * HeartEmoji update
 */
export type HeartEmojiUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeartEmoji
   */
  select?: Prisma.HeartEmojiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HeartEmoji
   */
  omit?: Prisma.HeartEmojiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HeartEmojiInclude<ExtArgs> | null
  /**
   * The data needed to update a HeartEmoji.
   */
  data: Prisma.XOR<Prisma.HeartEmojiUpdateInput, Prisma.HeartEmojiUncheckedUpdateInput>
  /**
   * Choose, which HeartEmoji to update.
   */
  where: Prisma.HeartEmojiWhereUniqueInput
}

/**
 * HeartEmoji updateMany
 */
export type HeartEmojiUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update HeartEmojis.
   */
  data: Prisma.XOR<Prisma.HeartEmojiUpdateManyMutationInput, Prisma.HeartEmojiUncheckedUpdateManyInput>
  /**
   * Filter which HeartEmojis to update
   */
  where?: Prisma.HeartEmojiWhereInput
  /**
   * Limit how many HeartEmojis to update.
   */
  limit?: number
}

/**
 * HeartEmoji updateManyAndReturn
 */
export type HeartEmojiUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeartEmoji
   */
  select?: Prisma.HeartEmojiSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the HeartEmoji
   */
  omit?: Prisma.HeartEmojiOmit<ExtArgs> | null
  /**
   * The data used to update HeartEmojis.
   */
  data: Prisma.XOR<Prisma.HeartEmojiUpdateManyMutationInput, Prisma.HeartEmojiUncheckedUpdateManyInput>
  /**
   * Filter which HeartEmojis to update
   */
  where?: Prisma.HeartEmojiWhereInput
  /**
   * Limit how many HeartEmojis to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HeartEmojiIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * HeartEmoji upsert
 */
export type HeartEmojiUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeartEmoji
   */
  select?: Prisma.HeartEmojiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HeartEmoji
   */
  omit?: Prisma.HeartEmojiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HeartEmojiInclude<ExtArgs> | null
  /**
   * The filter to search for the HeartEmoji to update in case it exists.
   */
  where: Prisma.HeartEmojiWhereUniqueInput
  /**
   * In case the HeartEmoji found by the `where` argument doesn't exist, create a new HeartEmoji with this data.
   */
  create: Prisma.XOR<Prisma.HeartEmojiCreateInput, Prisma.HeartEmojiUncheckedCreateInput>
  /**
   * In case the HeartEmoji was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.HeartEmojiUpdateInput, Prisma.HeartEmojiUncheckedUpdateInput>
}

/**
 * HeartEmoji delete
 */
export type HeartEmojiDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeartEmoji
   */
  select?: Prisma.HeartEmojiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HeartEmoji
   */
  omit?: Prisma.HeartEmojiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HeartEmojiInclude<ExtArgs> | null
  /**
   * Filter which HeartEmoji to delete.
   */
  where: Prisma.HeartEmojiWhereUniqueInput
}

/**
 * HeartEmoji deleteMany
 */
export type HeartEmojiDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which HeartEmojis to delete
   */
  where?: Prisma.HeartEmojiWhereInput
  /**
   * Limit how many HeartEmojis to delete.
   */
  limit?: number
}

/**
 * HeartEmoji without action
 */
export type HeartEmojiDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the HeartEmoji
   */
  select?: Prisma.HeartEmojiSelect<ExtArgs> | null
  /**
   * Omit specific fields from the HeartEmoji
   */
  omit?: Prisma.HeartEmojiOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.HeartEmojiInclude<ExtArgs> | null
}
