version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: learning_language_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: l1312
      POSTGRES_DB: learning_language
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
